service: Proyecto-noticias
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

useDotenv: True

functions:
  - ${file(serverless/users.yml)}
  - ${file(serverless/news.yml)}

plugins:
  - serverless-offline
